#! /usr/bin/env python3

"""
    Akash Singh
    akashsin@kth.se
"""
import numpy as nm
import math

L = 0.4
M = 0.39
b1 = 0.311
b2 = 0.078


def scara_IK(point):
    x = point[0]
    y = point[1]
    z = point[2]
    q = [0.0, 0.0, 0.0]

    x_1 = x-0.07
    q[2] = z
    q[1] = nm.arccos((x_1*x_1 + y*y - 0.3*.3 - 0.35*0.35)/(2*0.3*0.35))
    diff_ang = nm.arctan2(y,x_1)
    theta1 = nm.arcsin(0.35*nm.sin(q[1])/nm.sqrt(x_1*x_1 + y*y))
    q[0] = diff_ang - theta1
    return q



def kuka_IK(point, R, joint_positions):
    x = point[0]
    y = point[1]
    z = point[2] - b1
    q = joint_positions
    #it must contain 7 elements



    error_x = nm.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
    T07 = nm.zeros([4, 4])
    T07_shift = nm.zeros([4,1])
    J = nm.zeros([12, 7])

    while (all(i >=0.01 for i in abs(error_x))):

        q1 = q[0]
        q2 = q[1]
        q3 = q[2]
        q4 = q[3]
        q5 = q[4]
        q6 = q[5]
        q7 = q[6]

        T07[0,0] = -math.cos(q7)*(math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))))+math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        T07[0,1] = math.sin(q7)*(math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))))+math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        T07[0,2] = -math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        T07[0,3] = math.cos(q1)*math.sin(q2)*(-2.0/5.0)-math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))*(3.9E1/1.0E2)-math.cos(q1)*math.cos(q4)*math.sin(q2)*(3.9E1/1.0E2);
        T07[1,0] = math.cos(q7)*(math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))))-math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        T07[1,1] = -math.sin(q7)*(math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))))-math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        T07[1,2] = math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))-math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        T07[1,3] = math.sin(q1)*math.sin(q2)*(-2.0/5.0)+math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))*(3.9E1/1.0E2)-math.cos(q4)*math.sin(q1)*math.sin(q2)*(3.9E1/1.0E2);
        T07[2,0] = math.sin(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3))-math.cos(q7)*(math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))-math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)));
        T07[2,1] = math.cos(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3))+math.sin(q7)*(math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))-math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)));
        T07[2,2] = math.sin(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))+math.cos(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4));
        T07[2,3] = math.cos(q2)*(2.0/5.0)+math.cos(q2)*math.cos(q4)*(3.9E1/1.0E2)+math.cos(q3)*math.sin(q2)*math.sin(q4)*(3.9E1/1.0E2);
        T07[3,3] = 1.0


        T07_shift[0,0] = math.cos(q1)*math.sin(q2)*(-2.0/5.0)-math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))*(3.9E1/5.0E2)+math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))*(3.9E1/5.0E2)-math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))*(3.9E1/1.0E2)-math.cos(q1)*math.cos(q4)*math.sin(q2)*(3.9E1/1.0E2);
        T07_shift[1,0] = math.sin(q1)*math.sin(q2)*(-2.0/5.0)+math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))*(3.9E1/5.0E2)-math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))*(3.9E1/5.0E2)+math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))*(3.9E1/1.0E2)-math.cos(q4)*math.sin(q1)*math.sin(q2)*(3.9E1/1.0E2);
        T07_shift[2,0] = math.cos(q2)*(2.0/5.0)+math.cos(q2)*math.cos(q4)*(3.9E1/1.0E2)+math.sin(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))*(3.9E1/5.0E2)+math.cos(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4))*(3.9E1/5.0E2)+math.cos(q3)*math.sin(q2)*math.sin(q4)*(3.9E1/1.0E2);
        T07_shift[3,0] = 1.0

        J[0,0] = math.sin(q1)*math.sin(q2)*(2.0/5.0)-math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))*(3.9E1/5.0E2)+math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))*(3.9E1/5.0E2)-math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))*(3.9E1/1.0E2)+math.cos(q4)*math.sin(q1)*math.sin(q2)*(3.9E1/1.0E2);
        J[0,1] = math.cos(q1)*math.cos(q2)*(-2.0/5.0)-math.cos(q6)*(math.cos(q1)*math.cos(q2)*math.cos(q4)+math.cos(q1)*math.cos(q3)*math.sin(q2)*math.sin(q4))*(3.9E1/5.0E2)-math.sin(q6)*(math.cos(q5)*(math.cos(q1)*math.cos(q2)*math.sin(q4)-math.cos(q1)*math.cos(q3)*math.cos(q4)*math.sin(q2))+math.cos(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5))*(3.9E1/5.0E2)-math.cos(q1)*math.cos(q2)*math.cos(q4)*(3.9E1/1.0E2)-math.cos(q1)*math.cos(q3)*math.sin(q2)*math.sin(q4)*(3.9E1/1.0E2);
        J[0,2] = math.sin(q4)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))*(-3.9E1/1.0E2)-math.sin(q6)*(math.sin(q5)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q4)*math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))*(3.9E1/5.0E2)-math.cos(q6)*math.sin(q4)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))*(3.9E1/5.0E2);
        J[0,3] = math.cos(q6)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))*(-3.9E1/5.0E2)-math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))*(3.9E1/1.0E2)-math.cos(q5)*math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))*(3.9E1/5.0E2)+math.cos(q1)*math.sin(q2)*math.sin(q4)*(3.9E1/1.0E2);
        J[0,4] = math.sin(q6)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))*(-3.9E1/5.0E2);
        J[0,5] = math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))*(3.9E1/5.0E2)+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))*(3.9E1/5.0E2);
        J[1,0] = math.cos(q1)*math.sin(q2)*(-2.0/5.0)-math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))*(3.9E1/5.0E2)+math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))*(3.9E1/5.0E2)-math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))*(3.9E1/1.0E2)-math.cos(q1)*math.cos(q4)*math.sin(q2)*(3.9E1/1.0E2);
        J[1,1] = math.cos(q2)*math.sin(q1)*(-2.0/5.0)-math.cos(q6)*(math.cos(q2)*math.cos(q4)*math.sin(q1)+math.cos(q3)*math.sin(q1)*math.sin(q2)*math.sin(q4))*(3.9E1/5.0E2)-math.sin(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q1)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q1)*math.sin(q2))+math.sin(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5))*(3.9E1/5.0E2)-math.cos(q2)*math.cos(q4)*math.sin(q1)*(3.9E1/1.0E2)-math.cos(q3)*math.sin(q1)*math.sin(q2)*math.sin(q4)*(3.9E1/1.0E2);
        J[1,2] = math.sin(q4)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))*(3.9E1/1.0E2)+math.sin(q6)*(math.sin(q5)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))*(3.9E1/5.0E2)+math.cos(q6)*math.sin(q4)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))*(3.9E1/5.0E2);
        J[1,3] = math.cos(q6)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))*(3.9E1/5.0E2)+math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))*(3.9E1/1.0E2)+math.sin(q1)*math.sin(q2)*math.sin(q4)*(3.9E1/1.0E2)+math.cos(q5)*math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))*(3.9E1/5.0E2);
        J[1,4] = math.sin(q6)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))*(3.9E1/5.0E2);
        J[1,5] = math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))*(-3.9E1/5.0E2)-math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))*(3.9E1/5.0E2);
        J[2,1] = math.sin(q2)*(-2.0/5.0)-math.cos(q4)*math.sin(q2)*(3.9E1/1.0E2)-math.sin(q6)*(math.cos(q5)*(math.sin(q2)*math.sin(q4)+math.cos(q2)*math.cos(q3)*math.cos(q4))-math.cos(q2)*math.sin(q3)*math.sin(q5))*(3.9E1/5.0E2)-math.cos(q6)*(math.cos(q4)*math.sin(q2)-math.cos(q2)*math.cos(q3)*math.sin(q4))*(3.9E1/5.0E2)+math.cos(q2)*math.cos(q3)*math.sin(q4)*(3.9E1/1.0E2);
        J[2,2] = math.sin(q6)*(math.cos(q3)*math.sin(q2)*math.sin(q5)+math.cos(q4)*math.cos(q5)*math.sin(q2)*math.sin(q3))*(3.9E1/5.0E2)-math.sin(q2)*math.sin(q3)*math.sin(q4)*(3.9E1/1.0E2)-math.cos(q6)*math.sin(q2)*math.sin(q3)*math.sin(q4)*(3.9E1/5.0E2);
        J[2,3] = math.cos(q2)*math.sin(q4)*(-3.9E1/1.0E2)-math.cos(q6)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))*(3.9E1/5.0E2)+math.cos(q5)*math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4))*(3.9E1/5.0E2)+math.cos(q3)*math.cos(q4)*math.sin(q2)*(3.9E1/1.0E2);
        J[2,4] = math.sin(q6)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3))*(-3.9E1/5.0E2);
        J[2,5] = math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))*(3.9E1/5.0E2)-math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4))*(3.9E1/5.0E2);
        J[3,0] = -math.cos(q7)*(math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))))+math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[3,1] = -math.cos(q7)*(math.sin(q6)*(math.cos(q1)*math.cos(q2)*math.cos(q4)+math.cos(q1)*math.cos(q3)*math.sin(q2)*math.sin(q4))-math.cos(q6)*(math.cos(q5)*(math.cos(q1)*math.cos(q2)*math.sin(q4)-math.cos(q1)*math.cos(q3)*math.cos(q4)*math.sin(q2))+math.cos(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5)))-math.sin(q7)*(math.sin(q5)*(math.cos(q1)*math.cos(q2)*math.sin(q4)-math.cos(q1)*math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q1)*math.cos(q5)*math.sin(q2)*math.sin(q3));
        J[3,2] = math.sin(q7)*(math.cos(q5)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q4)*math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))+math.cos(q7)*(math.cos(q6)*(math.sin(q5)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q4)*math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))-math.sin(q4)*math.sin(q6)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[3,3] = -math.cos(q7)*(math.sin(q6)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2)))-math.sin(q5)*math.sin(q7)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2));
        J[3,4] = math.sin(q7)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))+math.cos(q6)*math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[3,5] = -math.cos(q7)*(math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))-math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))));
        J[3,6] = math.sin(q7)*(math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))))+math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[4,0] = math.sin(q7)*(math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))))+math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[4,1] = math.sin(q7)*(math.sin(q6)*(math.cos(q1)*math.cos(q2)*math.cos(q4)+math.cos(q1)*math.cos(q3)*math.sin(q2)*math.sin(q4))-math.cos(q6)*(math.cos(q5)*(math.cos(q1)*math.cos(q2)*math.sin(q4)-math.cos(q1)*math.cos(q3)*math.cos(q4)*math.sin(q2))+math.cos(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5)))-math.cos(q7)*(math.sin(q5)*(math.cos(q1)*math.cos(q2)*math.sin(q4)-math.cos(q1)*math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q1)*math.cos(q5)*math.sin(q2)*math.sin(q3));
        J[4,2] = math.cos(q7)*(math.cos(q5)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q4)*math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))-math.sin(q7)*(math.cos(q6)*(math.sin(q5)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q4)*math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))-math.sin(q4)*math.sin(q6)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[4,3] = math.sin(q7)*(math.sin(q6)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2)))-math.cos(q7)*math.sin(q5)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2));
        J[4,4] = math.cos(q7)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))-math.cos(q6)*math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[4,5] = math.sin(q7)*(math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))-math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))));
        J[4,6] = math.cos(q7)*(math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))))-math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[5,0] = -math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))+math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[5,1] = -math.cos(q6)*(math.cos(q1)*math.cos(q2)*math.cos(q4)+math.cos(q1)*math.cos(q3)*math.sin(q2)*math.sin(q4))-math.sin(q6)*(math.cos(q5)*(math.cos(q1)*math.cos(q2)*math.sin(q4)-math.cos(q1)*math.cos(q3)*math.cos(q4)*math.sin(q2))+math.cos(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5));
        J[5,2] = -math.sin(q6)*(math.sin(q5)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q4)*math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)))-math.cos(q6)*math.sin(q4)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3));
        J[5,3] = -math.cos(q6)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2));
        J[5,4] = -math.sin(q6)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[5,5] = math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[6,0] = -math.cos(q7)*(math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))))+math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[6,1] = -math.cos(q7)*(math.sin(q6)*(math.cos(q2)*math.cos(q4)*math.sin(q1)+math.cos(q3)*math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q1)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q1)*math.sin(q2))+math.sin(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5)))-math.sin(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q1)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q1)*math.sin(q2))-math.cos(q5)*math.sin(q1)*math.sin(q2)*math.sin(q3));
        J[6,2] = -math.sin(q7)*(math.cos(q5)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.cos(q4)*math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))-math.cos(q7)*(math.cos(q6)*(math.sin(q5)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))-math.sin(q4)*math.sin(q6)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[6,3] = math.cos(q7)*(math.sin(q6)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2)))+math.sin(q5)*math.sin(q7)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2));
        J[6,4] = -math.sin(q7)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))-math.cos(q6)*math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[6,5] = math.cos(q7)*(math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))-math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))));
        J[6,6] = -math.sin(q7)*(math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))))-math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[7,0] = math.sin(q7)*(math.sin(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3))))+math.cos(q7)*(math.sin(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[7,1] = -math.cos(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q1)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q1)*math.sin(q2))-math.cos(q5)*math.sin(q1)*math.sin(q2)*math.sin(q3))+math.sin(q7)*(math.sin(q6)*(math.cos(q2)*math.cos(q4)*math.sin(q1)+math.cos(q3)*math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q1)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q1)*math.sin(q2))+math.sin(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5)));
        J[7,2] = -math.cos(q7)*(math.cos(q5)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.cos(q4)*math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))+math.sin(q7)*(math.cos(q6)*(math.sin(q5)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))-math.sin(q4)*math.sin(q6)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[7,3] = -math.sin(q7)*(math.sin(q6)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2)))+math.cos(q7)*math.sin(q5)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2));
        J[7,4] = -math.cos(q7)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))+math.cos(q6)*math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[7,5] = -math.sin(q7)*(math.cos(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))-math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))));
        J[7,6] = -math.cos(q7)*(math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))+math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3))))+math.sin(q7)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[8,0] = -math.cos(q6)*(math.sin(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))+math.cos(q1)*math.cos(q4)*math.sin(q2))+math.sin(q6)*(math.cos(q5)*(math.cos(q4)*(math.sin(q1)*math.sin(q3)-math.cos(q1)*math.cos(q2)*math.cos(q3))-math.cos(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q3)*math.sin(q1)+math.cos(q1)*math.cos(q2)*math.sin(q3)));
        J[8,1] = -math.cos(q6)*(math.cos(q2)*math.cos(q4)*math.sin(q1)+math.cos(q3)*math.sin(q1)*math.sin(q2)*math.sin(q4))-math.sin(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q1)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q1)*math.sin(q2))+math.sin(q1)*math.sin(q2)*math.sin(q3)*math.sin(q5));
        J[8,2] = math.sin(q6)*(math.sin(q5)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)))+math.cos(q6)*math.sin(q4)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3));
        J[8,3] = math.cos(q6)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.cos(q5)*math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2));
        J[8,4] = math.sin(q6)*(math.sin(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))-math.cos(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[8,5] = -math.sin(q6)*(math.sin(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))-math.cos(q4)*math.sin(q1)*math.sin(q2))-math.cos(q6)*(math.cos(q5)*(math.cos(q4)*(math.cos(q1)*math.sin(q3)+math.cos(q2)*math.cos(q3)*math.sin(q1))+math.sin(q1)*math.sin(q2)*math.sin(q4))+math.sin(q5)*(math.cos(q1)*math.cos(q3)-math.cos(q2)*math.sin(q1)*math.sin(q3)));
        J[9,1] = -math.sin(q7)*(math.sin(q5)*(math.sin(q2)*math.sin(q4)+math.cos(q2)*math.cos(q3)*math.cos(q4))+math.cos(q2)*math.cos(q5)*math.sin(q3))+math.cos(q7)*(math.cos(q6)*(math.cos(q5)*(math.sin(q2)*math.sin(q4)+math.cos(q2)*math.cos(q3)*math.cos(q4))-math.cos(q2)*math.sin(q3)*math.sin(q5))-math.sin(q6)*(math.cos(q4)*math.sin(q2)-math.cos(q2)*math.cos(q3)*math.sin(q4)));
        J[9,2] = -math.sin(q7)*(math.cos(q3)*math.cos(q5)*math.sin(q2)-math.cos(q4)*math.sin(q2)*math.sin(q3)*math.sin(q5))-math.cos(q7)*(math.cos(q6)*(math.cos(q3)*math.sin(q2)*math.sin(q5)+math.cos(q4)*math.cos(q5)*math.sin(q2)*math.sin(q3))+math.sin(q2)*math.sin(q3)*math.sin(q4)*math.sin(q6));
        J[9,3] = -math.cos(q7)*(math.sin(q6)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.cos(q5)*math.cos(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)))+math.sin(q5)*math.sin(q7)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4));
        J[9,4] = math.sin(q7)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))+math.cos(q6)*math.cos(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3));
        J[9,5] = math.cos(q7)*(math.sin(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))+math.cos(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)));
        J[9,6] = math.cos(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3))+math.sin(q7)*(math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))-math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)));
        J[10,1] = -math.cos(q7)*(math.sin(q5)*(math.sin(q2)*math.sin(q4)+math.cos(q2)*math.cos(q3)*math.cos(q4))+math.cos(q2)*math.cos(q5)*math.sin(q3))-math.sin(q7)*(math.cos(q6)*(math.cos(q5)*(math.sin(q2)*math.sin(q4)+math.cos(q2)*math.cos(q3)*math.cos(q4))-math.cos(q2)*math.sin(q3)*math.sin(q5))-math.sin(q6)*(math.cos(q4)*math.sin(q2)-math.cos(q2)*math.cos(q3)*math.sin(q4)));
        J[10,2] = -math.cos(q7)*(math.cos(q3)*math.cos(q5)*math.sin(q2)-math.cos(q4)*math.sin(q2)*math.sin(q3)*math.sin(q5))+math.sin(q7)*(math.cos(q6)*(math.cos(q3)*math.sin(q2)*math.sin(q5)+math.cos(q4)*math.cos(q5)*math.sin(q2)*math.sin(q3))+math.sin(q2)*math.sin(q3)*math.sin(q4)*math.sin(q6));
        J[10,3] = math.sin(q7)*(math.sin(q6)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.cos(q5)*math.cos(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)))+math.cos(q7)*math.sin(q5)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4));
        J[10,4] = math.cos(q7)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))-math.cos(q6)*math.sin(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3));
        J[10,5] = -math.sin(q7)*(math.sin(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))+math.cos(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)));
        J[10,6] = -math.sin(q7)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3))+math.cos(q7)*(math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))-math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4)));
        J[11,1] = -math.sin(q6)*(math.cos(q5)*(math.sin(q2)*math.sin(q4)+math.cos(q2)*math.cos(q3)*math.cos(q4))-math.cos(q2)*math.sin(q3)*math.sin(q5))-math.cos(q6)*(math.cos(q4)*math.sin(q2)-math.cos(q2)*math.cos(q3)*math.sin(q4));
        J[11,2] = math.sin(q6)*(math.cos(q3)*math.sin(q2)*math.sin(q5)+math.cos(q4)*math.cos(q5)*math.sin(q2)*math.sin(q3))-math.cos(q6)*math.sin(q2)*math.sin(q3)*math.sin(q4);
        J[11,3] = -math.cos(q6)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.cos(q5)*math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4));
        J[11,4] = -math.sin(q6)*(math.sin(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))-math.cos(q5)*math.sin(q2)*math.sin(q3));
        J[11,5] = math.cos(q6)*(math.cos(q5)*(math.cos(q2)*math.sin(q4)-math.cos(q3)*math.cos(q4)*math.sin(q2))+math.sin(q2)*math.sin(q3)*math.sin(q5))-math.sin(q6)*(math.cos(q2)*math.cos(q4)+math.cos(q3)*math.sin(q2)*math.sin(q4));

        J_inv = nm.linalg.pinv(J)

        x_curr = T07_shift[0,0]
        y_curr = T07_shift[1,0]
        z_curr = T07_shift[2,0]

        error_cart = [x-x_curr, y-y_curr, z-z_curr]

        Rot_curr = T07[0:3,0:3]
        Rot_error = R - Rot_curr

        error_x[0] = error_cart[0]
        error_x[1] = error_cart[1]
        error_x[2] = error_cart[2]
        m = 3
        for i in range(3):
            for j in range(3):
                error_x[m] = Rot_error[i,j]
                m = m+1
        #print(error_x.shape)

        error_q = nm.dot(J_inv, error_x)
        q = q + error_q


    return q
